server:
    port: 8082
    context-path: /app
   

spring:
  application:
    name: spring-session-gemfire-client-server
  profiles:
    active: local
  session:
      urlMappings: /*
      maxInactiveIntervalInSeconds: 60 
gemfire:
  locator:
      host: localhost
      port: 10334



  
