server:
    port: 8083
    context-path: /APP 
   

spring:
  application:
    name: EurekaClient-Bank-PCF
  profiles:
    active: local
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
      - "org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration"
      
gemfire:
  locator:
      host: localhost
      port: 10334
datasource:
     connection:         
         local: 
            url: jdbc:hsqldb:mem:sessiondb
            

woa:
  session:
      urlMappings: /*
      maxInactiveIntervalInSeconds: 60