server:
    port: 8083
    context-path: /APP 
   

spring:
  application:
    name: Spring-Session-Gemfire-ClientServer
  profiles:
    active: local
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
      - "org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration"
  session:
      urlMappings: /*
      maxInactiveIntervalInSeconds: 60 
gemfire:
  locator:
      host: localhost
      port: 10334
datasource:
     connection:         
         local: 
            url: jdbc:hsqldb:mem:sessiondb
            


  
